exec bspwm
# xrandr --dpi 108
xrandr --output DVI-D-0 --primary --mode 1920x1080 --pos 1024x0 --rotate left --output HDMI-0 --mode 1280x1024 --pos 0x0 --rotate left --output DP-5 --off --output DP-4 --off --output DP-3 --mode 1440x900 --pos 2104x0 --rotate right --output DP-2 --off --output DP-1 --off --output DP-0 --off

