#! /bin/sh

sxhkd &
xrandr --dpi 108 --output DVI-D-0 --primary --mode 1920x1080 --pos 1024x0 --rotate left --output HDMI-0 --mode 1440x900 --pos 2104x552 --rotate normal --output DP-5 --off --output DP-4 --off --output DP-3 --mode 1280x1024 --pos 0x172 --rotate left --output DP-2 --off --output DP-1 --off --output DP-0 --off

export DISPLAY=:0
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx


bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc monitor DVI-D-0 -d 2 5
bspc monitor HDMI-0 -d 3 6
bspc monitor DP-3 -d 1 4


# others
ibus-daemon -d
ibus engine rime



